const express=require('express');const cors=require('cors');const fs=require('fs');const path=require('path');const crypto=require('crypto');const jwt=require('jsonwebtoken');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'mk-pizza-change-this-secret';const DATA=path.join(__dirname,'data.json');
app.use(cors());app.use(express.json({limit:'5mb'}));app.use(express.static(path.join(__dirname,'public')));
const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
const initial=()=>({company:{name:'MK Pizza & Ice Bar',address:'Abbas Chowk Collage Road Bhakkar',phone:'0316 9700025',tax:0,currency:'Rs'},users:[{id:'u-admin',name:'Administrator',username:'admin',password:'admin123',role:'admin',active:true},{id:'u-waiter',name:'Waiter',username:'waiter',password:'waiter123',role:'waiter',active:true},{id:'u-kitchen',name:'Kitchen',username:'kitchen',password:'kitchen123',role:'kitchen',active:true},{id:'u-cashier',name:'Cashier',username:'cashier',password:'cashier123',role:'cashier',active:true}],products:[{id:'p1',name:'Pizza',sku:'PIZ',price:850,stock:100,unit:'piece',category:'Pizza',active:true,variants:[{name:'Small',price:600},{name:'Medium',price:850},{name:'Large',price:1100},{name:'XL',price:1400}]},{id:'p2',name:'Shawarma',sku:'SHA',price:250,stock:100,unit:'piece',category:'Shawarma',active:true,variants:[{name:'Small',price:200},{name:'Medium',price:250},{name:'Large',price:320}]},{id:'p3',name:'Burger',sku:'BRG',price:450,stock:100,unit:'piece',category:'Burgers',active:true,variants:[{name:'Special',price:400},{name:'Chicken',price:420},{name:'Zinger',price:450}]},{id:'p4',name:'Biryani',sku:'BRY',price:250,stock:100,unit:'plate',category:'Biryani',active:true,variants:[{name:'Half',price:180},{name:'Full',price:300}]},{id:'p5',name:'Ice Cream',sku:'ICE',price:180,stock:100,unit:'scoop',category:'Ice Cream',active:true,variants:[{name:'1 Scoop',price:180},{name:'2 Scoops',price:320}]},{id:'p6',name:'Tea',sku:'TEA',price:100,stock:100,unit:'cup',category:'Drinks',active:true},{id:'p7',name:'Coffee',sku:'COF',price:180,stock:100,unit:'cup',category:'Drinks',active:true},{id:'p8',name:'Shake',sku:'SHK',price:300,stock:100,unit:'glass',category:'Shakes',active:true}],combos:[],orders:[],salesLedger:[],purchases:[],stockMoves:[],demands:[],expenses:[],customers:[],suppliers:[],riders:[],accounts:[],production:[],audit:[]});
function db(){if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(initial(),null,2));const d=JSON.parse(fs.readFileSync(DATA,'utf8'));for(const k of Object.keys(initial()))if(d[k]===undefined)d[k]=initial()[k];return d}function save(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{return res.status(401).json({error:'Login required'})}}function roles(...rs){return(req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({error:'Permission denied'})}function log(d,action,entity,id,meta={}){d.audit.push({id:uid(),at:now(),by:d.userName||'system',action,entity,entityId:id,...meta})}
app.get('/api/health',(q,s)=>s.json({ok:true,company:db().company}));app.get('/api/company',(q,s)=>s.json(db().company));
app.post('/api/login',(req,res)=>{const d=db(),u=d.users.find(x=>x.username===req.body.username&&x.password===req.body.password&&x.active!==false);if(!u)return res.status(401).json({error:'Invalid username or password'});res.json({token:jwt.sign({id:u.id,name:u.name,role:u.role},SECRET,{expiresIn:'12h'}),user:{id:u.id,name:u.name,role:u.role},company:d.company})});app.get('/api/me',auth,(q,s)=>s.json(q.user));
app.get('/api/products',(req,res)=>{const d=db(),q=String(req.query.q||'').toLowerCase();res.json(d.products.filter(p=>p.active!==false&&(!q||JSON.stringify(p).toLowerCase().includes(q))))});
app.post('/api/products',auth,roles('admin'),(req,res)=>{const d=db(),p={id:uid(),name:req.body.name,sku:req.body.sku||uid().slice(0,8),price:Number(req.body.price)||0,stock:Number(req.body.stock)||0,unit:req.body.unit||'piece',category:req.body.category||'General',active:true,variants:Array.isArray(req.body.variants)?req.body.variants:[]};if(!p.name)return res.status(400).json({error:'Name required'});d.products.push(p);save(d);res.status(201).json(p)});
app.put('/api/products/:id',auth,roles('admin'),(req,res)=>{const d=db(),p=d.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});Object.assign(p,req.body);save(d);res.json(p)});app.delete('/api/products/:id',auth,roles('admin'),(req,res)=>{const d=db(),p=d.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});p.active=false;save(d);res.json({ok:true})});
app.post('/api/products/bulk',auth,roles('admin'),(req,res)=>{const d=db(),rows=Array.isArray(req.body)?req.body:req.body.rows;if(!Array.isArray(rows))return res.status(400).json({error:'rows required'});rows.forEach(r=>d.products.push({id:uid(),name:r.name,sku:r.sku||uid().slice(0,8),price:Number(r.price)||0,stock:Number(r.stock)||0,unit:r.unit||'piece',category:r.category||'General',active:true,variants:r.variants||[]}));save(d);res.json({imported:rows.length})});
app.get('/api/products/export',auth,roles('admin'),(req,res)=>{const d=db();const head='name,sku,price,stock,unit,category';const csv=[head,...d.products.map(p=>[p.name,p.sku,p.price,p.stock,p.unit,p.category].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','))].join('\n');res.type('text/csv').send(csv)});
app.get('/api/orders',auth,(req,res)=>{const d=db();let x=d.orders;if(req.user.role==='waiter')x=x.filter(o=>o.createdBy===req.user.id);res.json(x.slice().reverse())});
function expandItems(d,body){const out=[];for(const i of body.items||[]){const p=d.products.find(x=>x.id===i.productId&&x.active!==false);if(!p)throw Error('Product not found');const qty=Number(i.qty);const variant=i.variant||null;const v=variant&&p.variants.find(x=>x.name===variant);const price=v?Number(v.price):Number(i.price||p.price);out.push({productId:p.id,name:p.name,variant,qty,price,total:price*qty,source:i.source||'single',components:i.components||[]})}return out}
function createOrder(d,b,user,status){const items=expandItems(d,b);if(!items.length)throw Error('Order items required');const subtotal=items.reduce((s,i)=>s+i.total,0);const o={id:uid(),number:'MK-'+Date.now(),items,subtotal,tax:Number(d.company.tax)||0,total:subtotal+(Number(d.company.tax)||0),orderType:b.orderType||'dine-in',table:b.table||null,customer:b.customer||null,riderId:b.riderId||null,note:b.note||'',paymentMethod:b.paymentMethod||'cash',createdBy:user?user.id:'online',createdAt:now(),status,history:[{status,by:user?user.name:'Online Customer',at:now()}]};return o}
app.post('/api/orders',auth,roles('waiter','admin'),(req,res)=>{try{const d=db(),o=createOrder(d,req.body,req.user,'awaiting_authorization');d.orders.push(o);save(d);res.status(201).json(o)}catch(e){res.status(400).json({error:e.message})}});app.post('/api/online/orders',(req,res)=>{try{const d=db(),o=createOrder(d,req.body,null,'pending');d.orders.push(o);save(d);res.status(201).json({orderNumber:o.number,status:o.status})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/orders/:id/status',auth,roles('admin','kitchen','cashier'),(req,res)=>{const d=db(),o=d.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Order not found'});const n=req.body.status;const allowed={admin:['authorized','sent_to_kitchen','cancelled'],kitchen:['preparing','ready'],cashier:['paid','closed']}[req.user.role]||[];if(!allowed.includes(n))return res.status(403).json({error:'Invalid status'});if(req.user.role==='admin'&&n==='authorized')o.items.forEach(i=>{const p=d.products.find(x=>x.id===i.productId);if(p)p.stock-=i.qty});o.status=n;o.history.push({status:n,by:req.user.name,at:now()});if(n==='paid'||n==='closed'){o.items.forEach(i=>d.salesLedger.push({id:uid(),orderId:o.id,orderNumber:o.number,productId:i.productId,item:i.name,variant:i.variant,qty:i.qty,amount:i.total,source:i.source,date:o.createdAt}))}save(d);res.json(o)});
app.get('/api/dashboard',auth,roles('admin','cashier'),(req,res)=>{const d=db(),today=new Date().toISOString().slice(0,10),os=d.orders.filter(o=>o.createdAt.startsWith(today));res.json({salesToday:os.filter(o=>['paid','closed'].includes(o.status)).reduce((s,o)=>s+o.total,0),ordersToday:os.length,pending:os.filter(o=>['pending','awaiting_authorization'].includes(o.status)).length,kitchen:os.filter(o=>['sent_to_kitchen','preparing'].includes(o.status)).length,ready:os.filter(o=>o.status==='ready').length,products:d.products.length,lowStock:d.products.filter(p=>p.stock<=5).length})});
const crud={riders:['admin'],users:['admin'],customers:['admin','cashier','waiter'],suppliers:['admin'],expenses:['admin'],accounts:['admin'],demands:['admin','waiter']};for(const [name,rs] of Object.entries(crud)){app.get('/api/'+name,auth,roles(...rs),(q,s)=>s.json(db()[name]));app.post('/api/'+name,auth,roles(...rs),(q,s)=>{const d=db(),v={id:uid(),...q.body,createdAt:now()};d[name].push(v);save(d);s.status(201).json(v)});app.put('/api/'+name+'/:id',auth,roles(...rs),(q,s)=>{const d=db(),v=d[name].find(x=>x.id===q.params.id);if(!v)return s.status(404).json({error:'Not found'});Object.assign(v,q.body);save(d);s.json(v)});app.delete('/api/'+name+'/:id',auth,roles('admin'),(q,s)=>{const d=db();d[name]=d[name].filter(x=>x.id!==q.params.id);save(d);s.json({ok:true})})}
app.post('/api/staff',auth,roles('admin'),(req,res)=>{const d=db(),u={id:uid(),name:req.body.name,username:req.body.username,password:req.body.password||'change-me',role:req.body.role||'waiter',active:true};d.users.push(u);save(d);res.status(201).json({...u,password:undefined})});
app.post('/api/demands',auth,roles('admin'),(req,res)=>{const d=db(),v={id:uid(),item:req.body.item,qty:Number(req.body.qty)||0,unit:req.body.unit||'kg',type:req.body.type||'purchase',supplierId:req.body.supplierId||null,status:'requested',createdAt:now()};d.demands.push(v);save(d);res.status(201).json(v)});
app.get('/api/analytics/items',auth,roles('admin'),(req,res)=>{const d=db(),from=req.query.from||'0000-01-01',to=req.query.to||'9999-12-31',m={};d.salesLedger.filter(x=>x.date.slice(0,10)>=from&&x.date.slice(0,10)<=to).forEach(x=>{const k=x.item+'|'+(x.variant||'');m[k]??={item:x.item,variant:x.variant||'Standard',qty:0,amount:0};m[k].qty+=x.qty;m[k].amount+=x.amount});res.json(Object.values(m))});
app.get('/api/analytics/demands',auth,roles('admin'),(req,res)=>{const d=db(),m={};d.demands.forEach(x=>{m[x.item]??={item:x.item,qty:0,unit:x.unit};m[x.item].qty+=Number(x.qty)||0});res.json(Object.values(m))});
app.post('/api/stock/adjust',auth,roles('admin'),(req,res)=>{const d=db(),p=d.products.find(x=>x.id===req.body.productId);if(!p)return res.status(404).json({error:'Product not found'});const qty=Number(req.body.qty);p.stock+=qty;d.stockMoves.push({id:uid(),productId:p.id,qty,type:req.body.type||'adjustment',note:req.body.note||'',at:now()});save(d);res.json(p)});
app.post('/api/production/yield',auth,roles('admin'),(req,res)=>{const d=db(),input=Number(req.body.inputQty),output=Number(req.body.outputQty);if(input<=0||output<0)return res.status(400).json({error:'Invalid quantities'});const loss=input-output;const r={id:uid(),material:req.body.material||'Meat',inputQty:input,inputUnit:req.body.inputUnit||'kg',outputQty:output,outputUnit:req.body.outputUnit||'kg',lossQty:loss,lossPercent:Number((loss/input*100).toFixed(2)),date:now(),note:req.body.note||''};d.production.push(r);save(d);res.json(r)});
app.get('/api/analytics/yield',auth,roles('admin'),(q,s)=>s.json(db().production));
app.get('/api/analytics/sales',auth,roles('admin'),(req,res)=>{const d=db(),from=req.query.from||'0000-01-01',to=req.query.to||'9999-12-31',os=d.orders.filter(o=>o.createdAt.slice(0,10)>=from&&o.createdAt.slice(0,10)<=to&&['paid','closed'].includes(o.status));res.json({orders:os.length,revenue:os.reduce((s,o)=>s+o.total,0),items:d.salesLedger.filter(x=>x.date.slice(0,10)>=from&&x.date.slice(0,10)<=to)})});
app.get('/api/export/all',auth,roles('admin'),(q,s)=>{const d=db();s.json(d)});app.get('/api/settings',auth,roles('admin'),(q,s)=>s.json(db().company));app.put('/api/settings',auth,roles('admin'),(q,s)=>{const d=db();d.company={...d.company,...q.body};save(d);s.json(d.company)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('MK Pizza POS '+PORT));