const express=require('express');const cors=require('cors');const fs=require('fs');const path=require('path');const crypto=require('crypto');const jwt=require('jsonwebtoken');
const app=express();const PORT=process.env.PORT||3000;const JWT_SECRET=process.env.JWT_SECRET||'mk-pizza-change-this-secret';const DATA=path.join(__dirname,'data.json');
app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const initial=()=>({company:{name:'MK Pizza & Ice Bar',address:'Abbas Chowk Collage Road Bhakkar',phone:'0316 9700025',tax:0,currency:'Rs'},users:[{id:'u-admin',name:'Administrator',username:'admin',password:'admin123',role:'admin'},{id:'u-waiter',name:'Waiter',username:'waiter',password:'waiter123',role:'waiter'},{id:'u-kitchen',name:'Kitchen',username:'kitchen',password:'kitchen123',role:'kitchen'},{id:'u-cashier',name:'Cashier',username:'cashier',password:'cashier123',role:'cashier'}],products:[{id:'p1',name:'Chicken Pizza',sku:'PIZ-001',price:850,stock:100,category:'Pizza',active:true},{id:'p2',name:'Cheese Pizza',sku:'PIZ-002',price:750,stock:100,category:'Pizza',active:true},{id:'p3',name:'Zinger Burger',sku:'BRG-001',price:450,stock:100,category:'Burgers',active:true},{id:'p4',name:'Fries',sku:'FRY-001',price:220,stock:100,category:'Fast Food',active:true},{id:'p5',name:'Cold Drink',sku:'DRK-001',price:120,stock:100,category:'Drinks',active:true}],orders:[],sessions:[]});
function db(){if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(initial(),null,2));return JSON.parse(fs.readFileSync(DATA,'utf8'))}function save(x){fs.writeFileSync(DATA,JSON.stringify(x,null,2))}
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace('Bearer ',''),JWT_SECRET);next()}catch{return res.status(401).json({error:'Login required'})}}function roles(...r){return(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:'Permission denied'})}
app.get('/api/health',(q,s)=>s.json({ok:true,company:'MK Pizza & Ice Bar'}));
app.get('/api/company',(q,s)=>s.json(db().company));
app.post('/api/login',(req,res)=>{const d=db(),u=d.users.find(x=>x.username===req.body.username&&x.password===req.body.password);if(!u)return res.status(401).json({error:'Invalid username or password'});const token=jwt.sign({id:u.id,name:u.name,role:u.role},JWT_SECRET,{expiresIn:'12h'});res.json({token,user:{id:u.id,name:u.name,role:u.role},company:d.company})});
app.get('/api/me',auth,(q,s)=>s.json(q.user));
app.get('/api/products',(req,res)=>{const d=db(),q=String(req.query.q||'').toLowerCase();res.json(d.products.filter(p=>p.active!==false&&(!q||`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(q))))});
app.post('/api/products',auth,roles('admin'),(req,res)=>{const d=db(),{name,sku,price,stock=0,category='General'}=req.body;if(!name||!sku||Number(price)<0)return res.status(400).json({error:'Invalid product'});if(d.products.some(p=>p.sku===sku))return res.status(409).json({error:'SKU exists'});const p={id:crypto.randomUUID(),name,sku,price:Number(price),stock:Number(stock),category,active:true};d.products.push(p);save(d);res.status(201).json(p)});
function makeOrder(d,body,user,status){if(!Array.isArray(body.items)||!body.items.length)throw Error('Order items required');const items=[];let subtotal=0;for(const i of body.items){const p=d.products.find(x=>x.id===i.productId&&x.active!==false);const qty=Number(i.qty);if(!p||!Number.isInteger(qty)||qty<1)throw Error('Invalid item');if(p.stock<qty)throw Error(`Insufficient stock: ${p.name}`);items.push({productId:p.id,name:p.name,qty,price:p.price,total:p.price*qty});subtotal+=p.price*qty}const tax=Number(d.company.tax)||0;const total=Math.max(0,subtotal+tax);const o={id:crypto.randomUUID(),number:`MK-${Date.now()}`,items,subtotal,tax,total,paymentMethod:body.paymentMethod||'cash',customer:body.customer||null,table:body.table||null,orderType:body.orderType||'dine-in',note:body.note||'',createdBy:user?user.id:'online',createdAt:new Date().toISOString(),status,history:[{status,by:user?user.name:'Online Customer',at:new Date().toISOString()}]};if(status!=='pending'){items.forEach(i=>d.products.find(p=>p.id===i.productId).stock-=i.qty)}return o}
app.post('/api/orders',auth,roles('waiter','admin'),(req,res)=>{try{const d=db(),o=makeOrder(d,req.body,req.user,'awaiting_authorization');d.orders.push(o);save(d);res.status(201).json(o)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/online/orders',(req,res)=>{try{const d=db(),o=makeOrder(d,req.body,null,'pending');d.orders.push(o);save(d);res.status(201).json({orderNumber:o.number,status:o.status})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/orders',auth,(req,res)=>{const d=db();let os=d.orders;if(req.user.role==='waiter')os=os.filter(o=>o.createdBy===req.user.id||o.status==='pending');res.json(os.slice().reverse())});
app.post('/api/orders/:id/status',auth,roles('admin','kitchen','cashier'),(req,res)=>{const d=db(),o=d.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Order not found'});const next=req.body.status;const allowed={admin:['authorized','cancelled','sent_to_kitchen'],kitchen:['preparing','ready'],cashier:['paid','closed']}[req.user.role]||[];if(!allowed.includes(next))return res.status(403).json({error:'Invalid status for your role'});if(req.user.role==='admin'&&next==='authorized'){if(!o.items.every(i=>{const p=d.products.find(x=>x.id===i.productId);return p&&p.stock>=i.qty}))return res.status(409).json({error:'Insufficient stock'});o.items.forEach(i=>d.products.find(p=>p.id===i.productId).stock-=i.qty)}o.status=next;o.history.push({status:next,by:req.user.name,at:new Date().toISOString()});save(d);res.json(o)});
app.get('/api/dashboard',auth,roles('admin','cashier'),(req,res)=>{const d=db(),today=new Date().toISOString().slice(0,10),os=d.orders.filter(o=>o.createdAt.startsWith(today));res.json({salesToday:os.filter(o=>['paid','closed'].includes(o.status)).reduce((s,o)=>s+o.total,0),ordersToday:os.length,pending:os.filter(o=>['awaiting_authorization','pending'].includes(o.status)).length,kitchen:os.filter(o=>['sent_to_kitchen','preparing'].includes(o.status)).length,ready:os.filter(o=>o.status==='ready').length,products:d.products.length,lowStock:d.products.filter(p=>p.stock<=5).length})});
app.get('/api/settings',auth,roles('admin'),(q,s)=>s.json(db().company));app.put('/api/settings',auth,roles('admin'),(req,res)=>{const d=db();d.company={...d.company,...req.body};save(d);res.json(d.company)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`MK Pizza POS on ${PORT}`));
